### ISSUE TITLE
Include guys and name but not number and address

### ISSUE THREAD

**Issue by josev814** [josev814/supercitymfg#9]

**Comment by josev814** [comment]
I need more information on this request.  What page is this pertaining to?  I assume only the contact page.  Also what address and numbers should not be included?  Are all emails and phone numbers to be removed from the contact page?

**Comment by josev814** [comment]
I need more information on this request. What page is this pertaining to? I assume only the contact page. Also what address and numbers should not be included? Are all emails and phone numbers to be removed from the contact page?

**Comment by weasek** [comment]
this is for the logo that will replace the business name at the top of the page.  I have a business crd and will see if I can work this image up tomorrow.

**Comment by josev814** [comment]
So, this is only pertaining to this issue, https://github.com/josev814/supercitymfg/issues/4 , and not it's own issue pertaining to the Contact Page?

**Comment by weasek** [comment]
Not sure I follow but I don't recall any changes needing done to the contact page.

**Comment by josev814** [comment]
Okay, these were just details added to the business logo issue then and weren't a separate task.
